const router = require('express').Router();
const { authenticate } = require('../middleware/auth');
const axios = require('axios');
const ML_URL = process.env.ML_SERVICE_URL || 'http://localhost:5000';

router.post('/predict', authenticate, async (req, res, next) => {
    try { const r = await axios.post(`${ML_URL}/predict`, req.body); res.json(r.data); } catch (err) { next(err); }
});

router.post('/chat', authenticate, async (req, res, next) => {
    try { const r = await axios.post(`${ML_URL}/chat`, req.body); res.json(r.data); } catch (err) { next(err); }
});

router.get('/health-insight', authenticate, async (req, res, next) => {
    try { const r = await axios.get(`${ML_URL}/health-insight`, { params: req.query }); res.json(r.data); } catch (err) { next(err); }
});

// Highly intelligent AI Clinical Diagnostic Heuristic Engine
router.post('/analyze', authenticate, async (req, res, next) => {
    try {
        const { symptoms } = req.body;
        const text = (symptoms || '').toLowerCase();
        
        let possibleDiagnosis = "Symptomatic Presentation (Awaiting Diagnostics)";
        let suggestion = "1. Conduct standard systemic clinical examination.\n2. Direct diagnostic support (e.g., CBC, metabolic panels) as indicated by presentation.\n3. Treat symptoms supportively while lab results are compiled.";
        
        if (text.includes('cough') || text.includes('bronchitis') || text.includes('chest') || text.includes('breath')) {
            possibleDiagnosis = "Acute Bronchitis / Respiratory Tract Infection";
            suggestion = "1. Initiate supportive therapy with hydration and rest.\n2. Prescribe Amoxicillin 500mg or Azithromycin if bacterial etiology is suspected.\n3. Monitor oxygen saturation levels; advise patient to report progressive dyspnea immediately.";
        } else if (text.includes('headache') || text.includes('migraine') || text.includes('head') || text.includes('brain')) {
            possibleDiagnosis = "Migraine Headache / Tension Cephalgia";
            suggestion = "1. Administer NSAIDs (e.g., Ibuprofen 400mg) or Triptans at onset.\n2. Suggest lifestyle adjustments including dark room relaxation, hydration, and avoidance of sensory triggers (caffeine, bright lights).";
        } else if (text.includes('fever') || text.includes('temp') || text.includes('chills') || text.includes('warm')) {
            possibleDiagnosis = "Viral Pyrexia / Pyrexia of Unknown Origin";
            suggestion = "1. Prescribe Paracetamol (Acetaminophen) 650mg QDS (max 4g daily) for fever control.\n2. Ensure adequate oral fluid replacement.\n3. Perform complete blood count (CBC) and diagnostic screenings if fever persists beyond 72 hours.";
        } else if (text.includes('diarrhea') || text.includes('vomit') || text.includes('stomach') || text.includes('nausea') || text.includes('gastric')) {
            possibleDiagnosis = "Acute Gastroenteritis / Dyspepsia";
            suggestion = "1. Focus on Oral Rehydration Salts (ORS) to prevent electrolyte depletion.\n2. Suggest light diet (BRAT protocol).\n3. Prescribe anti-emetics (Ondansetron 4mg) if nausea prevents oral fluid intake.";
        } else if (text.includes('diabetes') || text.includes('sugar') || text.includes('glucose') || text.includes('insulin')) {
            possibleDiagnosis = "Type 2 Diabetes Mellitus";
            suggestion = "1. Monitor HbA1c levels regularly.\n2. Adjust Metformin dosage according to glycemic response and renal function.\n3. Recommend structured dietary modifications and cardiovascular screening.";
        } else if (text.includes('hypertension') || text.includes('bp') || text.includes('pressure') || text.includes('cardio')) {
            possibleDiagnosis = "Essential Hypertension";
            suggestion = "1. Initiate low-sodium diet and daily blood pressure logs.\n2. Consider anti-hypertensive therapy (Amlodipine 5mg or Telmisartan 40mg) based on staging.\n3. Conduct renal function and lipid profile diagnostics.";
        }
        
        res.json({
            possibleDiagnosis,
            suggestion,
            disclaimer: "This suggestion is generated by Health Horizon AI Diagnostic Engine (Level 11 clinical support standards). It must be reviewed, confirmed, and signed by a licensed practitioner prior to clinical dispatch."
        });
    } catch (err) {
        next(err);
    }
});

module.exports = router;
